In [7]:
import numpy as np

dataLoaded = np.load('./BenchDataNmpy/tai20x15.npy')

dataLoaded[0]
 

array([[[94, 66, 10, 53, 26, 15, 65, 82, 10, 27, 93, 92, 96, 70, 83],
        [74, 31, 88, 51, 57, 78,  8,  7, 91, 79, 18, 51, 18, 99, 33],
        [ 4, 82, 40, 86, 50, 54, 21,  6, 54, 68, 82, 20, 39, 35, 68],
        [73, 23, 30, 30, 53, 94, 58, 93, 32, 91, 30, 56, 27, 92,  9],
        [78, 23, 21, 60, 36, 29, 95, 99, 79, 76, 93, 42, 52, 42, 96],
        [29, 61, 88, 70, 16, 31, 65, 83, 78, 26, 50, 87, 62, 14, 30],
        [18, 75, 20,  4, 91, 68, 19, 54, 85, 73, 43, 24, 37, 87, 66],
        [32, 52,  9, 49, 61, 35, 99, 62,  6, 62,  7, 80,  3, 57,  7],
        [85, 30, 96, 91, 13, 87, 82, 83, 78, 56, 85,  8, 66, 88, 15],
        [ 5, 59, 30, 60, 41, 17, 66, 89, 78, 88, 69, 45, 82,  6, 13],
        [90, 27,  1,  8, 91, 80, 89, 49, 32, 28, 90, 93,  6, 35, 73],
        [47, 43, 75,  8, 51,  3, 84, 34, 28, 60, 69, 45, 67, 58, 87],
        [65, 62, 97, 20, 31, 33, 33, 77, 50, 80, 48, 90, 75, 96, 44],
        [28, 21, 51, 75, 17, 89, 59, 56, 63, 18, 17, 30, 16,  7, 35],
        [57, 16, 42,

In [10]:
dataLoaded.shape[0]

10

In [11]:
dataLoaded[0][0]

array([[94, 66, 10, 53, 26, 15, 65, 82, 10, 27, 93, 92, 96, 70, 83],
       [74, 31, 88, 51, 57, 78,  8,  7, 91, 79, 18, 51, 18, 99, 33],
       [ 4, 82, 40, 86, 50, 54, 21,  6, 54, 68, 82, 20, 39, 35, 68],
       [73, 23, 30, 30, 53, 94, 58, 93, 32, 91, 30, 56, 27, 92,  9],
       [78, 23, 21, 60, 36, 29, 95, 99, 79, 76, 93, 42, 52, 42, 96],
       [29, 61, 88, 70, 16, 31, 65, 83, 78, 26, 50, 87, 62, 14, 30],
       [18, 75, 20,  4, 91, 68, 19, 54, 85, 73, 43, 24, 37, 87, 66],
       [32, 52,  9, 49, 61, 35, 99, 62,  6, 62,  7, 80,  3, 57,  7],
       [85, 30, 96, 91, 13, 87, 82, 83, 78, 56, 85,  8, 66, 88, 15],
       [ 5, 59, 30, 60, 41, 17, 66, 89, 78, 88, 69, 45, 82,  6, 13],
       [90, 27,  1,  8, 91, 80, 89, 49, 32, 28, 90, 93,  6, 35, 73],
       [47, 43, 75,  8, 51,  3, 84, 34, 28, 60, 69, 45, 67, 58, 87],
       [65, 62, 97, 20, 31, 33, 33, 77, 50, 80, 48, 90, 75, 96, 44],
       [28, 21, 51, 75, 17, 89, 59, 56, 63, 18, 17, 30, 16,  7, 35],
       [57, 16, 42, 34, 37, 26, 68

In [15]:
dataLoaded[0][1]

array([[ 7, 13,  5,  8,  4,  3, 11, 12,  9, 15, 10, 14,  6,  1,  2],
       [ 5,  6,  8, 15, 14,  9, 12, 10,  7, 11,  1,  4, 13,  2,  3],
       [ 2,  9, 10, 13,  7, 12, 14,  6,  1,  3,  8, 11,  5,  4, 15],
       [ 6,  3, 10,  7, 11,  1, 14,  5,  8, 15, 12,  9, 13,  2,  4],
       [ 8,  9,  7, 11,  5, 10,  3, 15, 13,  6,  2, 14, 12,  1,  4],
       [ 6,  4, 13, 14, 12,  5, 15,  8,  3,  2, 11,  1, 10,  7,  9],
       [13,  4,  8,  9, 15,  7,  2, 12,  5,  6,  3, 11,  1, 14, 10],
       [12,  6,  1,  8, 13, 14, 15,  2,  3,  9,  5,  4, 10,  7, 11],
       [11, 12,  7, 15,  1,  2,  3,  6, 13,  5,  9,  8, 10, 14,  4],
       [ 7, 12, 10,  3,  9,  1, 14,  4, 11,  8,  2, 13, 15,  5,  6],
       [ 5,  8, 14,  1,  6, 13,  7,  9, 15, 11,  4,  2, 12, 10,  3],
       [ 3, 15,  1, 13,  7, 11,  8,  6,  9, 10, 14,  2,  4, 12,  5],
       [ 6,  9, 11,  3,  4,  7, 10,  1, 14,  5,  2, 12, 13,  8, 15],
       [ 9, 15,  5, 14,  6,  7, 10,  2, 13,  8, 12, 11,  4,  3,  1],
       [11,  9, 13,  7,  5,  2, 14

In [1]:
import numpy as np

dataGenerated = np.load('./DataGen/generatedData3_2_Seed200.npy')

In [5]:
dataGenerated[0]

array([[[26, 16],
        [68, 42],
        [55, 76]],

       [[ 1,  2],
        [ 1,  2],
        [ 2,  1]]])

In [ ]:
dataGenerated[0]

####### Action Selected #######:  0
####### Action Selected #######:  2
####### Action Selected #######:  1
####### Action Selected #######:  4
####### Action Selected #######:  3
####### Action Selected #######:  5
Instance1 makespan: 173.0

M1:(26) --0--  (68) --> 94  ---- (55) --> 149
M2:(16) --78-- (42) --> 136 --0-- (76) --> 212 

M1:(26) --0--  (68) --> 94  ---- (55) --> 149
M2:--10--(16) --0-- (42) --> 152 --0-- (76) --> 212 

In [21]:
import numpy as np

durations= np.array([[26, 16],
       [68, 42],
       [55, 76]])

orders= np.array([[1, 2],
       [1, 2],
       [2, 1]])

dataset = [(durations, orders)]

dataset
#dataset[0][0].shape[0]

[(array([[26, 16],
         [68, 42],
         [55, 76]]),
  array([[1, 2],
         [1, 2],
         [2, 1]]))]

In [ ]:
(array([[26, 16],
       [68, 42],
       [55, 76]]), array([[1, 2],
       [1, 2],
       [2, 1]])